# Generated by Django 4.1 on 2022-08-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='parent',
            new_name='parents',
        ),
    ]
