# Generated by Django 4.1 on 2022-08-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_parent_item_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='news.item'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='polls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='news.item'),
        ),
    ]
