# Generated by Django 4.1 on 2022-08-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_kid_item_alter_parts_polls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('by', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('time', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.item')),
            ],
        ),
    ]
