# Generated by Django 4.1 on 2022-08-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_parent_comment_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='parent',
        ),
    ]
