# Generated by Django 4.1 on 2022-08-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment_deleted_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', max_length=10),
        ),
        migrations.DeleteModel(
            name='Kid',
        ),
    ]
