# Generated by Django 4.1 on 2022-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
