# Generated by Django 4.1 on 2022-08-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_with_api',
            field=models.BooleanField(default=False),
        ),
    ]
